# Dockerfile.connect_module
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy connect module files
COPY connect_module/ /app

# Install dependencies
RUN pip install --no-cache-dir flask==2.2.5 requests pandas

# Expose port for connect module
EXPOSE 5002

# Run the application
CMD ["python", "app.py"]