# connect-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
      - name: connect
        image: kaviya6369/connect-module:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 5002