apiVersion: apps/v1
kind: Deployment
metadata:
  name: module1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: module1
  template:
    metadata:
      labels:
        app: module1
    spec:
      containers:
      - name: module1
        image: kaviya6369/module1-image:v1   # explicitly v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000